; WeatherAlert — ELEGOO ESP-32 Super Starter Kit
; https://docs.platformio.org/en/latest/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; ELEGOO 0.96" SSD1306 OLED (lesson 2.14)
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.12.1
    bblanchon/ArduinoJson @ ^7.4.2

build_flags =
    -DCORE_DEBUG_LEVEL=3

upload_port = /dev/cu.usbserial-0001
monitor_port = /dev/cu.usbserial-0001